[font]
normal.family = "JetBrainsMono Nerd Font"
bold.family = "JetBrainsMono Nerd Font"
italic.family = "JetBrainsMono Nerd Font"
bold_italic.family = "JetBrainsMono Nerd Font"

size = 12.0

[general]
import = [
    "~/.config/alacritty/themes/noctalia.toml"
]

[[keyboard.bindings]]
key = "Return"
mods = "Shift"
chars = "\u001b\r"
