[packages.arch]
pacman = [
  "age",
  "alacritty",
  "aspnet-runtime-bin",
  "aspnet-targeting-pack-bin",
  "bitwarden",
  "bitwarden-cli",
  "btop",
  "chezmoi",
  "claude-code",
  "discord",
  "docker",
  "docker-compose",
  "dotnet-host-bin",
  "dotnet-runtime-bin",
  "dotnet-sdk-bin",
  "dotnet-targeting-pack-bin",
  "fastfetch",
  "fluxcd",
  "freerdp",
  "git",
  "git-delta",
  "git-lfs",
  "github-cli",
  "go",
  "go-yq",
  "helm",
  "jdk21-openjdk",
  "jq",
  "just",
  "krdc",
  "krew",
  "kubectl",
  "kubectx",
  "kustomize",
  "localsend",
  "maven",
  "meld",
  "mise",
  "mpv",
  "pulumi",
  "ripgrep",
  "rustdesk-bin",
  "rustup",
  "satty",
  "sops",
  "syncthing",
  "ttf-jetbrains-mono",
  "ttf-jetbrains-mono-nerd",
  "virt-manager",
  "wl-clipboard",
  "youtube-music",
  "yt-dlp",
  "zen-browser-bin",
]

aur = [
  "aws-cli-bin",
  "freelens-bin",
  "github-copilot-cli",
  "lens-bin",
  "oh-my-posh-bin",
  "openvpn3",
  "powershell-bin",
  "proton-pass-cli-bin",
  "pulumi-language-dotnet",
  "qt6ct-kde",
  "rider",
  "slack-desktop-wayland",
  "virtio-win",
  "visual-studio-code-bin",
]

[packages.arch.personal]
pacman = [
  "talhelper",
  "talosctl",
]

aur = [
  "bottles",
  "raiderio-client",
  "warcraftlogsuploader",
  "whisper.cpp-model-large-v3-turbo",
  "whisper.cpp-vulkan",
  "whispering-bin",
  "wowup-cf-bin",
]
